### ISSUE TITLE
Invincible and Lag

### ISSUE THREAD

**Issue by Fallenare** [fiote/RunicPowerValheimMod#1]
Hello, I downloaded Runic Power to add to my mods list, but it seems to be slightly outdated for the current 0.216.9 game version.
Something in the mod is causing player/NPC damage rolls to flag the error pasted below. Structure damage seems to work fine.
Is there any way you can update this mod, or would you allow me to have another mod dev look into creating a patch or rewrite?
If you are able to work on this yourself, I would be interested in discussing the details further.

[Error : Unity Log] MissingFieldException: Field 'HitData.m_statusEffect' not found.
Stack trace:
(wrapper dynamic-method) Character.DMDCharacter::RPC_Damage(Character,long,HitData)
System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at <695d1cc93cca45069c528c15c9fdd749>:0)
Rethrow as TargetInvocationException: Exception has been thrown by the target of an invocation.
System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at <695d1cc93cca45069c528c15c9fdd749>:0)
System.Reflection.MethodBase.Invoke (System.Object obj, System.Object[] parameters) (at <695d1cc93cca45069c528c15c9fdd749>:0)
System.Delegate.DynamicInvokeImpl (System.Object[] args) (at <695d1cc93cca45069c528c15c9fdd749>:0)
System.MulticastDelegate.DynamicInvokeImpl (System.Object[] args) (at <695d1cc93cca45069c528c15c9fdd749>:0)
System.Delegate.DynamicInvoke (System.Object[] args) (at <695d1cc93cca45069c528c15c9fdd749>:0)
RoutedMethod`1[T].Invoke (System.Int64 rpc, ZPackage pkg) (at <2959d3c128e64c61a08dcc9bb6744ec3>:0)
ZNetView.HandleRoutedRPC (ZRoutedRpc+RoutedRPCData rpcData) (at <2959d3c128e64c61a08dcc9bb6744ec3>:0)
ZRoutedRpc.HandleRoutedRPC (ZRoutedRpc+RoutedRPCData data) (at <2959d3c128e64c61a08dcc9bb6744ec3>:0)
ZRoutedRpc.InvokeRoutedRPC (System.Int64 targetPeerID, ZDOID targetZDO, System.String methodName, System.Object[] parameters) (at <2959d3c128e64c61a08dcc9bb6744ec3>:0)
ZNetView.InvokeRPC (System.String method, System.Object[] parameters) (at <2959d3c128e64c61a08dcc9bb6744ec3>:0)
(wrapper dynamic-method) Character.DMDCharacter::Damage(Character,HitData)
(wrapper dynamic-method) Attack.DMDAttack::DoMeleeAttack(Attack)
(wrapper dynamic-method) Attack.DMDAttack::OnAttackTrigger(Attack)
Humanoid.OnAttackTrigger () (at <2959d3c128e64c61a08dcc9bb6744ec3>:0)
CharacterAnimEvent.Hit () (at <2959d3c128e64c61a08dcc9bb6744ec3>:0)

**Comment by fiote** [comment]
The mod is updated to current game's version now. If you still have problems, please open another issue :)
