### ISSUE TITLE
no bug but request

### ISSUE THREAD

**Issue by GracefulUni** [fiote/RunicPowerValheimMod#2]
Can you please add this to thunderstore =o

**Comment by fiote** [comment]
I'm not sure I will. I just realized thunderstore have no incentives for developers. On nexus I can 'trade' download points for game keys.

**Comment by GracefulUni** [comment]
> I'm not sure I will. I just realized thunderstore have no incentives for developers. On nexus I can 'trade' download points for game keys.

Thats unfortunate, think mod looks really cool and was wanting to add to my modpacks potentially and try it out

**Comment by fiote** [comment]
I would guess you could add it manually, but I understand if you don't. Sorry about that!
